name: Unit Tests
run-name: Run Unit Tests
on:
  push:
    branches:
      - main
jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Unit Tests
        run: |
          chmod +x ./tests/unit-test.sh
          ./tests/unit-test.sh
        shell: bash
